<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Build3" failures="1" tests="2" name="Test(failed)" time="0.034" errors="0" timestamp="2023-06-09T11:58:16 EDT">
  <testcase classname="interview.testng.practice.Class4Listener" name="failTest" time="0.006">
    <failure type="java.lang.AssertionError" message="Test Case Supposed to be Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Case Supposed to be Failed expected [true] but found [false]
at interview.testng.practice.Class4Listener.failTest(Class4Listener.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="interview.testng.practice.Class4Listener" name="failSkip" time="0.0">
    <skipped/>
  </testcase> <!-- failSkip -->
  <testcase classname="interview.testng.practice.Class4Listener" name="loginAndVerify" time="0.0">
    <ignored/>
  </testcase> <!-- loginAndVerify -->
</testsuite> <!-- Test(failed) -->
